otel-collector-pipeline:
  workers: 1
  delay: 500 # milliseconds
  source:
    otel_trace_source:
      port: 21890
      ssl: false
      health_check_service: true
  buffer:
    bounded_blocking:
      buffer_size: 2048
      batch_size: 256
  sink:
    - pipeline: 
        name: raw-sink
    - pipeline: 
        name: map-sink
raw-sink:
  delay: 100
  source:
    pipeline:
      name: otel-collector-pipeline
  processor:
    - otel_trace_raw_prepper:
  sink:
    - opensearch:
        hosts: [ "http://opensearch:9200" ]
        insecure: true
        trace_analytics_raw: true
        number_of_shards: 1
        number_of_replicas: 0
map-sink:
  delay: 100
  source:
    pipeline:
      name: otel-collector-pipeline
  processor:
    - service_map_stateful:
  sink:
    - opensearch:
        hosts: [ "http://opensearch:9200" ]
        insecure: true
        number_of_shards: 1
        number_of_replicas: 0
        trace_analytics_service_map: true
          # index_type: trace_analytics_raw

