otel-collector-pipeline:
  workers: 1
  delay: 500 # milliseconds
  source:
    otel_trace_source:
      port: 21890
      ssl: false
      health_check_service: true
  buffer:
    bounded_blocking:
      buffer_size: 2048
      batch_size: 256
  prepper:
    - otel_trace_raw_prepper:
  sink:
    - opensearch:
        hosts: [ "http://opensearch:9200" ]
        insecure: true
        index: traces

